package Student;

import DBConnection.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Joe
 */
public class Add_student extends javax.swing.JFrame {

    PreparedStatement ps;
    ResultSet rs;
    Connection con = null;
    
    public Add_student() {
        initComponents();
        this.setLocationRelativeTo(null);
        addStd.setVisible(false);
        addStd.setEnabled(false);
        studentID.setText(String.valueOf(loadStdID()));
        Ac_Year.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Academic_semester = new javax.swing.JLabel();
        groupID = new javax.swing.JTextField();
        subGroupID = new javax.swing.JTextField();
        studentID = new javax.swing.JTextField();
        SgroupNo = new javax.swing.JComboBox();
        groupNo = new javax.swing.JComboBox();
        clear = new javax.swing.JButton();
        addStd = new javax.swing.JButton();
        generateID = new javax.swing.JButton();
        Semester = new javax.swing.JComboBox();
        Ac_Year = new javax.swing.JComboBox();
        Programme = new javax.swing.JComboBox();
        Academic_year = new javax.swing.JLabel();
        clear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Student Groups");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Student ID :");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Programme :");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Sub-Group ID :");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Group Number :");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Sub-Group Number :");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Group ID :");

        Academic_semester.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Academic_semester.setText("Academic Semester :");

        groupID.setEditable(false);
        groupID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        subGroupID.setEditable(false);
        subGroupID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        studentID.setEditable(false);
        studentID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDActionPerformed(evt);
            }
        });

        SgroupNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SgroupNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sub Group", "1", "2" }));

        groupNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        groupNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Group Number", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15" }));
        groupNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupNoActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 255, 0));
        clear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(51, 102, 255));
        clear.setText("Clear");
        clear.setPreferredSize(new java.awt.Dimension(79, 30));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        addStd.setBackground(new java.awt.Color(255, 255, 0));
        addStd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addStd.setForeground(new java.awt.Color(51, 102, 255));
        addStd.setText("Add New Student");
        addStd.setEnabled(false);
        addStd.setPreferredSize(new java.awt.Dimension(185, 30));
        addStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStdActionPerformed(evt);
            }
        });

        generateID.setBackground(new java.awt.Color(255, 255, 0));
        generateID.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        generateID.setForeground(new java.awt.Color(51, 102, 255));
        generateID.setText("Generate ID's");
        generateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateIDActionPerformed(evt);
            }
        });

        Semester.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Semester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Semester", "1st Semester", "2nd Semester" }));

        Ac_Year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ac_Year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Year", "1st Year", "2nd Year", "3rd Year", "4th Year" }));

        Programme.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Programme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Programme", "IT", "SE", "ISE", "CSNE", "CS", "IN", "DS" }));

        Academic_year.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Academic_year.setText("Academic Year :");

        clear1.setBackground(new java.awt.Color(255, 255, 0));
        clear1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        clear1.setForeground(new java.awt.Color(51, 102, 255));
        clear1.setText("Close");
        clear1.setPreferredSize(new java.awt.Dimension(79, 30));
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Academic_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Academic_year, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Programme, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SgroupNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(groupNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Ac_Year, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Semester, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addComponent(addStd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subGroupID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(groupID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(generateID, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(269, 269, 269))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(Academic_year, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Academic_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(Ac_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Semester, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(groupNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(SgroupNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Programme, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(groupID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(subGroupID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(generateID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(addStd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47))))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        Ac_Year.setSelectedIndex(0);
        Semester.setSelectedIndex(0);
        groupID.setText("");
        subGroupID.setText("");
        groupNo.setSelectedIndex(0);
        SgroupNo.setSelectedIndex(0);
        Programme.setSelectedIndex(0);
    }//GEN-LAST:event_clearActionPerformed

    private void addStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStdActionPerformed
        String student_id = studentID.getText();
        int academic_Year = Ac_Year.getSelectedIndex();
        int academic_semester = Semester.getSelectedIndex();
        String group_id = groupID.getText();
        String sub_id = subGroupID.getText();
        int g_number = groupNo.getSelectedIndex();
        int sgroup_number = SgroupNo.getSelectedIndex();
        String program = (String)Programme.getSelectedItem();
        program = Programme.getSelectedItem().toString();
        

        //SQL query
        String quary = "INSERT INTO student(id, academic_year, academic_semester, groupID, subGroup_ID, groupNB, subGroupNB, programme)VALUES(?,?,?,?,?,?,?,?)";
        
        try {
            ps = DBConnect.getConnection().prepareStatement(quary);
            
            ps.setString(1, student_id);
            ps.setInt(2, academic_Year);
            ps.setInt(3, academic_semester);
            ps.setString(4, group_id);
            ps.setString(5, sub_id);
            ps.setInt(6, g_number);
            ps.setInt(7, sgroup_number);
            ps.setString(8, program);
            
            if(ps.executeUpdate() == 1){
                JOptionPane.showMessageDialog(null, "Data Added Successfully");
                clearActionPerformed(evt);
                studentID.setText(String.valueOf(loadStdID()));
            }else{
                JOptionPane.showMessageDialog(null, "Error!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Add_student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addStdActionPerformed

    private void generateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateIDActionPerformed
        Boolean Error = false;
        String ProgrammeV = (String)Programme.getSelectedItem();
        String Programme1 = Programme.getSelectedItem().toString();
                
        String Year = String.valueOf(Ac_Year.getSelectedIndex());
        String semester = String.valueOf(Semester.getSelectedIndex());
        String groupNb = String.valueOf(groupNo.getSelectedIndex());
        String SubgroupNb = String.valueOf(SgroupNo.getSelectedIndex());
        
        
        if(Year.equals("0")){
            JOptionPane.showMessageDialog(null, "Please select Year","Error", JOptionPane.ERROR_MESSAGE);
            Error = true;
        }
        if(Error == false && semester.equals("0")){
            JOptionPane.showMessageDialog(null, "Please select Semester","Error", JOptionPane.ERROR_MESSAGE);
            Error = true;
        }
        if(Error == false && groupNb.equals("0")){
            JOptionPane.showMessageDialog(null, "Please select Group","Error", JOptionPane.ERROR_MESSAGE);
            Error = true;
        }
        if(Error == false && SubgroupNb.equals("0")){
            JOptionPane.showMessageDialog(null, "Please select Sub Group","Error", JOptionPane.ERROR_MESSAGE);
            Error = true;
        }
        if(Error == false && Programme1.equals("0")){
            JOptionPane.showMessageDialog(null, "Please select Programme","Error", JOptionPane.ERROR_MESSAGE);
            Error = true;
        }
        
        if(Error){
            JOptionPane.showMessageDialog(null, "Please check all fields ","Error", JOptionPane.ERROR_MESSAGE);
        }else{
            String gID = "Y"+Year+".S"+semester+"."+Programme1+"."+groupNb;
            String subgID = "Y"+Year+".S"+semester+"."+Programme1+"."+groupNb+"."+SubgroupNb;
            groupID.setText(gID);
            subGroupID.setText(subgID);

            addStd.setVisible(true);
            addStd.setEnabled(true);
        }

    }//GEN-LAST:event_generateIDActionPerformed

    private void groupNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupNoActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_clear1ActionPerformed

    
    public int loadStdID(){
        String quary = "SELECT * FROM student ORDER BY id DESC LIMIT 1";
        
        try {
            ps = DBConnect.getConnection().prepareStatement(quary);
            rs = ps.executeQuery();
            while(rs.next()){
                int StdID = rs.getInt("id") + 1;
                return StdID;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Add_student.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Ac_Year;
    private javax.swing.JLabel Academic_semester;
    private javax.swing.JLabel Academic_year;
    private javax.swing.JComboBox Programme;
    private javax.swing.JComboBox Semester;
    private javax.swing.JComboBox SgroupNo;
    private javax.swing.JButton addStd;
    private javax.swing.JButton clear;
    private javax.swing.JButton clear1;
    private javax.swing.JButton generateID;
    private javax.swing.JTextField groupID;
    private javax.swing.JComboBox groupNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField studentID;
    private javax.swing.JTextField subGroupID;
    // End of variables declaration//GEN-END:variables
}
